### ISSUE TITLE
ServiceDesk client workorder page aborts: Error in 'select' success callback: Cannot read property 'supportStart' of undefined

### ISSUE THREAD

**Issue by realtdegen** [Vantiq/Blueprints#28]
ServiceDesk client crashes in workorder page while trying to leave to another page

The client has been aborted due to an execution error:
Error in 'select' success callback: Cannot read property 'supportStart' of undefined

TypeError: Error in 'select' success callback: Cannot read property 'supportStart' of undefined
    at ClientCallbackEvents.js:4390:41
    at ClientCallbackEvents.js:195:13
    at Function.a.executeCallbackFunctionSuccess (https://api.vantiq.com/ui/rtc/main-min.js?random=8872:346:1500)
    at https://api.vantiq.com/ui/rtc/main-min.js?random=8872:346:2138
    at https://api.vantiq.com/ui/rtc/main-min.js?random=8872:100:439
    at fu (https://api.vantiq.com/ui/lib/angular/angular-min.js:2:94090)
    at https://api.vantiq.com/ui/lib/angular/angular-min.js:2:94312
    at fD.$eval (https://api.vantiq.com/ui/lib/angular/angular-min.js:2:102286)
    at fD.$digest (https://api.vantiq.com/ui/lib/angular/angular-min.js:2:100564)
    at fD.$apply (https://api.vantiq.com/ui/lib/angular/angular-min.js:2:102591)

![image](https://user-images.githubusercontent.com/50694969/100812201-be47f100-343c-11eb-88af-58a25a1f9e6f.png)

**Comment by realtdegen** [comment]
@steve-langley is this an issue probably more to be concerned about ? I've seen this happening two times tonight but not sure how to reproduce at will

**Comment by steve-langley** [comment]
The callstack indicates that some of your event handler code is doing a "select" and there is an error in its "success" callback where it is trying to reference the "supportStart" property of a null object. Without seeing your code I can't tell you more, but if you are running under the Chrome debugger you should be able to  look at line 4390 of ClientCallbackEvents.js to see where that is happening. (That's the file we generate that contains all of your event handler code concatenated together.) The callstack can't point you right to the event handler because it's inside the asynchronous "success" callback of a "select", so the actual method is not on the stack at the time of the error.

**Comment by realtdegen** [comment]
at the end of the day it looks like the current type Customers existent in FSM Blueprint is lacking the requested properties supportStart and supportEnd as determined by the "Associate Button" onClick handler "// lookup warranty" section of the "WorkOrders" page; maybe the Customers Types update including these two new properties supportStart/supportEnd is in some other branch existent

{
  "adminAccessLevel" : "ars_readWrite",
  "audited" : false,
  "encapsulated" : false,
  "foreignKeys" : null,
  "groupEnabled" : false,
  "groupRequired" : false,
  "indexes" : [ {
    "keys" : [ "id" ],
    "options" : {
      "unique" : true
    }
  } ],
  "maxObjects" : 0,
  "maxStorage" : 0,
  "metadata" : false,
  "name" : "Customers",
  "naturalKey" : [ "id" ],
  "properties" : {
    "address" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "companyname" : {
      "encrypted" : false,
      "multi" : false,
      "required" : true,
      "type" : "String",
      "unique" : false
    },
    "contacts" : {
      "encrypted" : false,
      "multi" : true,
      "required" : false,
      "type" : "Object",
      "unique" : false
    },
    "email" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "facebook" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "faxnumber" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "geolocation" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "GeoJSON",
      "unique" : false
    },
    "googleplus" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "id" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "industry" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "linkedin" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "locations" : {
      "encrypted" : false,
      "multi" : true,
      "required" : false,
      "type" : "Object",
      "unique" : false
    },
    "phonenumber" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "primaryfirstname" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "primarylastname" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "products" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "Object",
      "unique" : false
    },
    "twitter" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    },
    "website" : {
      "encrypted" : false,
      "multi" : false,
      "required" : false,
      "type" : "String",
      "unique" : false
    }
  },
  "role" : "standard",
  "userAccessLevel" : "ars_readWrite",
  "volatile" : false
}

client.popupPage("ticketlistpopup", "Select a Ticket to associate to the Work Order", null, function(response){   
    if (response){

        page.data.Workorders.customer = response.customer;
        page.data.Workorders.customerId = response.customerId;
        page.data.Workorders.priority = response.priority;
        page.data.Workorders.impact = response.impact;
        page.data.Workorders.ticketId = response.id;
        page.data.Workorders.type = response.type;


		page.data.Workorders.initializePropertyToDefaultValue("address");
		page.data.Workorders.initializePropertyToDefaultValue("location");


		// get the customer support status
		var cparams = {where:{id:page.data.Workorders.customerId}};

        select("Customers", cparams, client, function(response){
            response = response[0];
            var fDate,lDate,cDate;
            fDate = Date.parse(response.supportStart);
            lDate = Date.parse(response.supportEnd);

            var d = new Date();
            cDate = d.getTime();

            if((cDate <= lDate && cDate >= fDate)){
                page.data.supportstatus = "UNDER SUPPORT";
            } else {
                page.data.supportstatus = "OUT OF SUPPORT";
            }    
        });


		if(response.assignedTo) 
            page.data.Workorders.servicedeskowner = response.assignedTo;
        
		var cid = response.customerId;

		// get the list of locations for the customer
		var param = {where:{customerid:{"$eq":cid}}};

        select("Locations", param, client, function(response){
            console.log("Success --- " + JSON.stringify(response));
            var listItems = [{"value":"- select -", "label":"- select -"}];
            $(response).each(function(index, item) {
                var value = item.id;
                var obj = {"value":value, "label":item.name};
                listItems.push(obj);
            });
            var locationList = client.getWidget("LocationDroplist");
            locationList.enumeratedList = listItems;
        });

        // lookup warranty
        var params = {where:{id:page.data.customerId}};
        select("Customers", params, function(response){
                console.log("SUCCESS: " + JSON.stringify(response));
                // check warranty
                var fDate,lDate,cDate;
                fDate = Date.parse(response[0].supportStart);
                lDate = Date.parse(response[0].supportEnd);
                page.data.supportStart = response[0].supportStart;
                page.data.supportEnd = response[0].supportEnd;

                var d = new Date();
                cDate = d.getTime();

                if((cDate <= lDate && cDate >= fDate)){
                    page.data.supportstatus = "UNDER SUPPORT";
                } else {
                    page.data.supportstatus = "OUT OF SUPPORT";
                }	
        });
    }
});

**Comment by realtdegen** [comment]
nice one :-)

The client has been aborted due to an execution error:
Error in 'select' success callback: log.info is not a function

TypeError: Error in 'select' success callback: log.info is not a function
    at ClientCallbackEvents.js:4404:9
    at ClientCallbackEvents.js:195:13
    at Function.a.executeCallbackFunctionSuccess (https://dev.vantiq.com/ui/rtc/main-min.js?random=8092:346:1500)
    at https://dev.vantiq.com/ui/rtc/main-min.js?random=8092:346:2138
    at https://dev.vantiq.com/ui/rtc/main-min.js?random=8092:100:439
    at fu (https://dev.vantiq.com/ui/lib/angular/angular-min.js:2:94090)
    at https://dev.vantiq.com/ui/lib/angular/angular-min.js:2:94312
    at fD.$eval (https://dev.vantiq.com/ui/lib/angular/angular-min.js:2:102286)
    at fD.$digest (https://dev.vantiq.com/ui/lib/angular/angular-min.js:2:100564)
    at fD.$apply (https://dev.vantiq.com/ui/lib/angular/angular-min.js:2:102591)


![image](https://user-images.githubusercontent.com/50694969/100863243-91272d00-3494-11eb-9c2d-a41fb8771e76.png)
